/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface AuthorizationGatewayInterface extends utils.Interface {
  functions: {
    "getSignedJoinApproval(address,address,uint256[],bool,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getSignedJoinApproval"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSignedJoinApproval",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSignedJoinApproval",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AuthorizationGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AuthorizationGatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSignedJoinApproval(
      crowdtainerAddress: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      quantities: PromiseOrValue<BigNumberish>[],
      _enableReferral: PromiseOrValue<boolean>,
      _referrer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { signature: string }>;
  };

  getSignedJoinApproval(
    crowdtainerAddress: PromiseOrValue<string>,
    addr: PromiseOrValue<string>,
    quantities: PromiseOrValue<BigNumberish>[],
    _enableReferral: PromiseOrValue<boolean>,
    _referrer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getSignedJoinApproval(
      crowdtainerAddress: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      quantities: PromiseOrValue<BigNumberish>[],
      _enableReferral: PromiseOrValue<boolean>,
      _referrer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getSignedJoinApproval(
      crowdtainerAddress: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      quantities: PromiseOrValue<BigNumberish>[],
      _enableReferral: PromiseOrValue<boolean>,
      _referrer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSignedJoinApproval(
      crowdtainerAddress: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      quantities: PromiseOrValue<BigNumberish>[],
      _enableReferral: PromiseOrValue<boolean>,
      _referrer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
