/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type MetadataStruct = {
  crowdtainerId: PromiseOrValue<BigNumberish>;
  tokenId: PromiseOrValue<BigNumberish>;
  currentOwner: PromiseOrValue<string>;
  claimed: PromiseOrValue<boolean>;
  unitPricePerType: [
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>
  ];
  quantities: [
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>
  ];
  productDescription: [
    PromiseOrValue<string>,
    PromiseOrValue<string>,
    PromiseOrValue<string>,
    PromiseOrValue<string>
  ];
  numberOfProducts: PromiseOrValue<BigNumberish>;
};

export type MetadataStructOutput = [
  BigNumber,
  BigNumber,
  string,
  boolean,
  [BigNumber, BigNumber, BigNumber, BigNumber],
  [BigNumber, BigNumber, BigNumber, BigNumber],
  [string, string, string, string],
  BigNumber
] & {
  crowdtainerId: BigNumber;
  tokenId: BigNumber;
  currentOwner: string;
  claimed: boolean;
  unitPricePerType: [BigNumber, BigNumber, BigNumber, BigNumber];
  quantities: [BigNumber, BigNumber, BigNumber, BigNumber];
  productDescription: [string, string, string, string];
  numberOfProducts: BigNumber;
};

export interface IMetadataServiceInterface extends utils.Interface {
  functions: {
    "uri((uint256,uint256,address,bool,uint256[4],uint256[4],string[4],uint256))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "uri"): FunctionFragment;

  encodeFunctionData(functionFragment: "uri", values: [MetadataStruct]): string;

  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;

  events: {};
}

export interface IMetadataService extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMetadataServiceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    uri(arg0: MetadataStruct, overrides?: CallOverrides): Promise<[string]>;
  };

  uri(arg0: MetadataStruct, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    uri(arg0: MetadataStruct, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    uri(arg0: MetadataStruct, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    uri(
      arg0: MetadataStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
